# --- General ---
CONFIG_EVENTS=y
CONFIG_THREAD_NAME=y
CONFIG_REBOOT=y
CONFIG_WATCHDOG=y

# --- Networking ---
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_MAX_CONN=10
CONFIG_NET_MAX_CONTEXTS=10
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_IPV4_AUTO=n
CONFIG_NET_DHCPV4=y

# --- Wi-Fi ---
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_WIFI_INIT_PRIORITY=60

# --- Storage (NVS Flash) ---
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_FLASH_PAGE_LAYOUT=y

# --- Hardware ---
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_CHARACTER_FRAMEBUFFER=y

# --- HEAD / STACK ---
CONFIG_LOG_BUFFER_SIZE=1024
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1536
CONFIG_NET_MGMT_EVENT_STACK_SIZE=1024
CONFIG_NET_TCP_WORKQ_STACK_SIZE=512
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_ISR_STACK_SIZE=32768
CONFIG_NET_RX_STACK_SIZE=4096
CONFIG_NET_TX_STACK_SIZE=4096

# --- DEBUG ---
CONFIG_LOG=n
CONFIG_PRINTK=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_THREAD_ANALYZER=n
CONFIG_THREAD_ANALYZER_AUTO=n
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=30